### ISSUE TITLE
Complete mandatory Slides per Scene

### ISSUE THREAD

**Issue by luisgizirian** [movement-disorders/therappeye#11]
Right now, each `Scene` has 1 `Slide` defined during construction.

Each `Scene` should have 2 `Slide`s:
* Instructions `Slide`. Displays a short sentence that instructs what to do next (i.e. *"Follow the circle with your eyes. Head still!"*)
* Action `Slide`: where the animation happens (i.e. `CircleAnimationSlide`)

Given the scene duration, we'll take a sec or two for instructions display and the rest will be assigned to the "Action `Slide`". The scene will receive its running time from the presentation, then take assign 2 seconds to the first slide, and the rest goes for the Animation slide.

- Presentation: 20 secs total running time (distributed evenly across Scenes) (out-scoped)
- Scene A: 10 secs. 2 for the intro and the rest (8 secs) goes to the animation slide.
- Scene B: 10 secs. 2 for the intro and the rest (8 secs) goes to the animation slide.

The minimum Presentation runtime will be 10 secs. (out-scoped)

> out-scoped means: this requirement doesn't belong to the scope of this Issue. Assumed.

**Hint:** if Instruction `Slide` won't vary on format, at build time may just receive the Sentence (string) to setup.

**Comment by David-J-Tinley** [comment]
Hi @luisgizirian, I just returned from  a short vacation. Is there anything specific I could work on. I installed SFML 2.6.x and have my fork of therappeye up to date with yours.

**Comment by luisgizirian** [comment]
Hi @David-J-Tinley. Hope had a nice break! Sure! This (#11) is an interesting one to get the infrastructure ready to later focus over animations.

I'd say #11 and #9 are the 2 to follow. One step at a time :)

**Comment by David-J-Tinley** [comment]
Sounds good to me, thank you!

**Comment by David-J-Tinley** [comment]
hi @luisgizirian, I had a quick question. Are you able to run the program in its current state? I am not able to compile the program unless I comment out the `presentation.runPresentation(window, shape);` in main.cpp. I am not sure if it just me having the issue with the `runPresentation` function? Without that function I can compile it just fine. Thank you!

**Comment by luisgizirian** [comment]
@David-J-Tinley, I can confirm it compiles ok on 2 different systems. Can you please share the error you're getting on-screen?

**Comment by David-J-Tinley** [comment]
<img width="1470" alt="Screenshot 2023-08-06 at 12 29 04 PM" src="https://github.com/movement-disorders/therappeye/assets/89220527/52bf2a8e-7f80-4d0c-b2d5-33277393437c">
(above) Here is the error I get when I try to compile it normally.
<img width="1470" alt="Screenshot 2023-08-06 at 12 29 50 PM" src="https://github.com/movement-disorders/therappeye/assets/89220527/6ddb7368-69ab-4eb8-a53f-d3dfe8c4a18b">
(above) Here is the command I use to compile. Since this is a Mac I use the SFML frameworks instead of doing the `-lsfml-xxxx` for the libraries in the command. The SFML website recommends using the frameworks for all MacOS.
<img width="1470" alt="Screenshot 2023-08-06 at 12 30 50 PM" src="https://github.com/movement-disorders/therappeye/assets/89220527/ae47ffab-8902-46a4-8c3c-de610b3f39c1">
(above) And here the program compiles when I comment out `presentation.runPresentation(window, shape);`. I am able to compile and run all of the example code from the SFML website as well. Thank you!

**Comment by luisgizirian** [comment]
Looks to me that there's a missing `.cpp` source file in the command. Please try it like this (without commenting the `presentation.runPresentation(...)` line.

```
clang++ -g -Wall -std=c++17 src/main.cpp src/presentation.cpp -o main -F /Library/Frameworks -framework sfml-window -framework sfml-graphics -framework sfml-system
```
Same command but adding ` src/presentation.cpp` to the sources list.

Let me know how it goes @David-J-Tinley  :)

**Comment by David-J-Tinley** [comment]
@luisgizirian You are correct! Thank you for the help, that answer makes sense. Have a good day!
