### ISSUE TITLE
Circle doesn't move around while blinking

### ISSUE THREAD

**Issue by luisgizirian** [movement-disorders/therappeye#2]
It's supposed to move randomly across the window, without ever exceeding its edges. But it always shows up in the same spot.

**Comment by David-J-Tinley** [comment]
Hi, I was wondering if I could be assigned this issue? Thank you for your time!

**Comment by luisgizirian** [comment]
> Hi, I was wondering if I could be assigned this issue? Thank you for your time!

Of course @David-J-Tinley. You're assigned. Let me know if you need extra information as this is a new project that's still in an idea-phase.

**Comment by David-J-Tinley** [comment]
@luisgizirian sounds good, thank you! I will get started!

**Comment by luisgizirian** [comment]
Happy to have you on board @David-J-Tinley. Thank you!

**Comment by David-J-Tinley** [comment]
Hi @luisgizirian, I had a few questions about this project. I am currently using a Mac with the newer M2 chip (but I also have a Windows 11 computer as well) so I have not been working on the CUDA build for this project. I have just been working with the `main.cpp` and the other header and source files for it. I noticed there seems to be some unfinished code in these files. Would you like me to fill in the code? I am able to compile and build the project but nothing really happens during its runtime. I think its just from some missing class definitions and so on. I'd love to be a part of filling out this build. Let me know what you are thinking or I you think this is all because I'm using a newer Mac I'll be happy to transfer the work to my Windows computer and see how it goes? Either way, thank you and have a good day!

**Comment by luisgizirian** [comment]
Thank you for your appreciations @David-J-Tinley, Please let me know what you think about this PR (https://github.com/movement-disorders/therappeye/pull/7) which intention is to set a better ground, taking the first step towards maturing from the original idea.

Also, check issue #4

[I'll tackle all your comments in an additional reply]

**Comment by luisgizirian** [comment]
[here's the additional reply]

Given PR #7 (branch: `introducing-presentation-hierarchy`), compiling and running with visible results has improved. Please keep using the system that's more comfortable for your situation. We'd like that those who choose to involve, keep working on the platform they need.

Don't worry about CUDA, as it's a possible improvement to discuss down-the-line. I was playing with it as I could get my hands on a Jetson Orin Nano Dev Kit.

About the structure and missing class definitions, #7 gives a more complete initial path in that sense, having cleared unused filed and created a set of base classes to satisfy #4.

I think #7 will allow us a better starting point, having took care of: an elaborated idea, a base class hierarchy, seeing results when running after building in Linux (ARM) and Windows 11 (Intel x86_64). I'd really like to merge it into `main` and move from there,

The issue that originally gave birth to this, remains there ready to be tackled, so you may resume once past this.

Enjoy the rest of your day!

**Comment by David-J-Tinley** [comment]
Thank you for the explanation @luisgizirian, I see that you have a new pull request waiting to be merged so once that happens I will update my fork of the repository with the changes you made and work with them from there.

**Comment by luisgizirian** [comment]
@David-J-Tinley, if the situation doesn't change after refreshing with the latest bits, here's a hint on SFML (a prerequisite) and M chips (https://stackoverflow.com/questions/69720807/how-do-i-use-sfml-on-apple-m1-mac)

**Comment by David-J-Tinley** [comment]
Thank you @luisgizirian!
